
ALTER TABLE INGREDIENT
ADD CONSTRAINT UNIQUE (NAME),
MODIFY CONTAINS_LACTOSE BOOLEAN NOT NULL,
MODIFY VEGETARIAN BOOLEAN NOT NULL,
MODIFY VEGAN BOOLEAN NOT NULL,
MODIFY GLUTEN_FREE BOOLEAN NOT NULL;
