 -- Replicate the top 5 joins found in the picture sql-joins.

SELECT M.NAME
FROM MEAL M
LEFT JOIN INGREDIENT I
on I.MEAL_ID = M.MEAL_ID;

SELECT M.NAME
FROM MEAL M
LEFT JOIN INGREDIENT I
on I.MEAL_ID = M.MEAL_ID
WHERE M.MEAL_ID IS NULL;

SELECT M.NAME
FROM MEAL M
INNER JOIN INGREDIENT I
ON M.MEAL_ID = I.MEAL_ID;

SELECT M.NAME
FROM MEAL M
RIGHT JOIN INGREDIENT I
ON M.MEAL_ID = I.MEAL_ID;

SELECT M.NAME
FROM MEAL M
RIGHT JOIN INGREDIENT I
ON M.MEAL_ID = I.MEAL_ID
WHERE M.MEAL_ID IS NULL;