SELECT * FROM MEAL WHERE PRICE<15;

SELECT * FROM INGREDIENT WHERE VEGETARIAN;

SELECT * FROM MEAL WHERE CALORIES>500;

SELECT * FROM MEAL WHERE PRICE >15 AND PRICE <16;

SELECT * FROM INGREDIENT WHERE NOT CONTAINS_LACTOSE AND GLUTEN_FREE;

SELECT * FROM MEAL WHERE PRICE <16 OR CALORIES >600;

SELECT * FROM INGREDIENT WHERE VEGAN OR GLUTEN_FREE;

SELECT * FROM MEAL WHERE NAME = 'Pesto Pasta';

SELECT * FROM INGREDIENT WHERE CONTAINS_LACTOSE;

SELECT * FROM MEAL WHERE PRICE >20 OR CALORIES <800;